language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11
os:
  - linux

#jobs:
#  exclude:
#  - language: java
#    jdk: openjdk8
#    os: osx

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pci
after_success:
  - mvn clean test jacoco:report coveralls:report -Pci
