#name: Maven And Coveralls 
name: GitHub CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] #, macOS-latest] // TODO

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ['1.8', '11', '15']
    - name: Build with Maven
      run: mvn clean install # -DskipTests=true

#    - name: Coveralls GitHub Action
#      uses: coverallsapp/github-action@v1.0.1
#      with:
#          github-token: ${{ secrets.github_token }}
#          parallel: true
